
public class RegistrarExamen extends javax.swing.JPanel {
	   protected Hash hashTable;
	    
	    
	    public RegistrarExamen() {
	        initComponents();
	        
	        //listLinked.toString1();
	        //instancia hash con 31 (n° días del mes)
	        hashTable= new Hash(31);
	    }
	   

	    /**
	     * This method is called from within the constructor to initialize the form.
	     * WARNING: Do NOT modify this code. The content of this method is always
	     * regenerated by the Form Editor.
	     */
	    @SuppressWarnings("unchecked")
	    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	    private void initComponents() {

	        jLabel1 = new javax.swing.JLabel();
	        jLabel2 = new javax.swing.JLabel();
	        tfnombreCurso = new javax.swing.JTextField();
	        jLabel3 = new javax.swing.JLabel();
	        tfNombreProfesor = new javax.swing.JTextField();
	        jLabel4 = new javax.swing.JLabel();
	        tfFechaExamen = new javax.swing.JTextField();
	        jLabel5 = new javax.swing.JLabel();
	        tfAulaExamen = new javax.swing.JTextField();
	        jLabel6 = new javax.swing.JLabel();
	        tfDuracionExamen = new javax.swing.JTextField();
	        btnRegistrar = new javax.swing.JButton();
	        jScrollPane1 = new javax.swing.JScrollPane();
	        table = new javax.swing.JTable();
	        btnEliminar = new javax.swing.JButton();

	        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
	        jLabel1.setText("Datos del Examen:");

	        jLabel2.setText("Nombre Curso:");

	        tfnombreCurso.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                tfnombreCursoActionPerformed(evt);
	            }
	        });

	        jLabel3.setText("Nombre Profesor:");

	        tfNombreProfesor.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                tfNombreProfesorActionPerformed(evt);
	            }
	        });

	        jLabel4.setText("Fecha Examen:");

	        tfFechaExamen.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                tfFechaExamenActionPerformed(evt);
	            }
	        });

	        jLabel5.setText("Aula Examen:");

	        tfAulaExamen.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                tfAulaExamenActionPerformed(evt);
	            }
	        });

	        jLabel6.setText("Duración Examen:");

	        tfDuracionExamen.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                tfDuracionExamenActionPerformed(evt);
	            }
	        });

	        btnRegistrar.setText("Registrar Examen");
	        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                btnRegistrarActionPerformed(evt);
	            }
	        });

	        table.setModel(new javax.swing.table.DefaultTableModel(
	            new Object [][] {

	            },
	            new String [] {
	                "Nombre Curso", "Nombre Profesor", "Fecha Examen", "Aula Examen", "Duración Examen"
	            }
	        ) {
	            Class[] types = new Class [] {
	                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
	            };
	            boolean[] canEdit = new boolean [] {
	                false, false, false, false, false
	            };

	            public Class getColumnClass(int columnIndex) {
	                return types [columnIndex];
	            }

	            public boolean isCellEditable(int rowIndex, int columnIndex) {
	                return canEdit [columnIndex];
	            }
	        });
	        jScrollPane1.setViewportView(table);

	        btnEliminar.setText("Eliminar");
	        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                btnEliminarActionPerformed(evt);
	            }
	        });

	        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
	        this.setLayout(layout);
	        layout.setHorizontalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(layout.createSequentialGroup()
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addGroup(layout.createSequentialGroup()
	                        .addContainerGap()
	                        .addComponent(jLabel1))
	                    .addGroup(layout.createSequentialGroup()
	                        .addGap(164, 164, 164)
	                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                            .addComponent(jLabel2)
	                            .addComponent(jLabel3)
	                            .addComponent(jLabel4)
	                            .addComponent(jLabel5)
	                            .addComponent(jLabel6))
	                        .addGap(50, 50, 50)
	                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                            .addComponent(tfDuracionExamen, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
	                            .addComponent(tfAulaExamen, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
	                            .addComponent(tfFechaExamen, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
	                            .addComponent(tfNombreProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
	                            .addComponent(tfnombreCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
	                    .addGroup(layout.createSequentialGroup()
	                        .addGap(259, 259, 259)
	                        .addComponent(btnRegistrar)))
	                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
	            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
	                .addContainerGap()
	                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
	                .addComponent(btnEliminar)
	                .addGap(24, 24, 24))
	        );
	        layout.setVerticalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(layout.createSequentialGroup()
	                .addContainerGap()
	                .addComponent(jLabel1)
	                .addGap(10, 10, 10)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jLabel2)
	                    .addComponent(tfnombreCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jLabel3)
	                    .addComponent(tfNombreProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jLabel4)
	                    .addComponent(tfFechaExamen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jLabel5)
	                    .addComponent(tfAulaExamen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jLabel6)
	                    .addComponent(tfDuracionExamen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addGap(27, 27, 27)
	                .addComponent(btnRegistrar)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addGroup(layout.createSequentialGroup()
	                        .addGap(37, 37, 37)
	                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
	                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
	                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
	                        .addComponent(btnEliminar)
	                        .addGap(314, 314, 314))))
	        );
	    }// </editor-fold>//GEN-END:initComponents

	    private void tfnombreCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfnombreCursoActionPerformed
	        // TODO add your handling code here:
	    }//GEN-LAST:event_tfnombreCursoActionPerformed

	    private void tfNombreProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNombreProfesorActionPerformed
	        // TODO add your handling code here:
	    }//GEN-LAST:event_tfNombreProfesorActionPerformed

	    private void tfFechaExamenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFechaExamenActionPerformed
	        // TODO add your handling code here:
	    }//GEN-LAST:event_tfFechaExamenActionPerformed

	    private void tfAulaExamenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAulaExamenActionPerformed
	        // TODO add your handling code here:
	    }//GEN-LAST:event_tfAulaExamenActionPerformed

	    private void tfDuracionExamenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDuracionExamenActionPerformed
	        // TODO add your handling code here:
	    }//GEN-LAST:event_tfDuracionExamenActionPerformed

	    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
	       try {
	           String curso = tfnombreCurso.getText();
	           String profesor = tfNombreProfesor.getText();
	           SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");//el formato de dd/MM/yyyy
	           Date fechaExamen = sdf.parse(tfFechaExamen.getText());
	           String aulaExamen= tfAulaExamen.getText();
	           int  duracion= Integer.parseInt(tfDuracionExamen.getText());
	           Examen ex = new Examen(profesor, curso,fechaExamen,aulaExamen, duracion);
	           hashTable.insert(ex);
	           addRow(ex);
	           JOptionPane.showMessageDialog(null,"Examen Registrado Correctamente.");
	           clearFields();
	       } catch (ParseException ex) {
	           JOptionPane.showMessageDialog(null,"Ocurrió un error. Verifique sus datos.");
	       }
	        
	        
	    }//GEN-LAST:event_btnRegistrarActionPerformed

	    public void addRow(Examen ex){
	        DefaultTableModel model = (DefaultTableModel) table.getModel(); //obtiene el modelo
	        //agrega la fila
	        model.addRow(new Object[]{ex.getNombreCurso(),ex.getNombreProfesor(),tfFechaExamen.getText(),ex.getUbicacionExamen(),
	        ex.getDuracionExamen()});
	    }
	    
	    public void clearFields(){
	        tfnombreCurso.setText("");
	        tfNombreProfesor.setText("");
	        tfFechaExamen.setText("");
	        tfAulaExamen.setText("");
	        tfDuracionExamen.setText("");
	    }
	    
	    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
	       try {
	           int index = table.getSelectedRow();
	           if (index<0){
	               JOptionPane.showMessageDialog(null,"Seleccione una fila.");
	               return;
	           }
	           String curso =table.getModel().getValueAt(index, 0).toString();
	           String profesor =table.getModel().getValueAt(index,1).toString();
	           SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");//el formato de dd/MM/yyyy
	           Date fechaExamen = sdf.parse(table.getModel().getValueAt(index, 2).toString());
	           String aula =table.getModel().getValueAt(index, 3).toString();
	           Integer duracion =Integer.parseInt(table.getModel().getValueAt(index, 4).toString());
	          ((DefaultTableModel)table.getModel()).removeRow(index);
	           hashTable.remove(new Examen(profesor, curso,fechaExamen, aula, duracion));
	       } catch (ParseException ex) {
	           Logger.getLogger(RegistrarExamen.class.getName()).log(Level.SEVERE, null, ex);
	       }
	    }//GEN-LAST:event_btnEliminarActionPerformed

